flags: {}
packages:
- '.'
- location:
    git: https://github.com/dbp/groundhog-postgres-snap
    commit: 05f2ab84db8e68cc5f4d3d03b86571348e55c962
  extra-dep: true
- location:
    git: https://github.com/dbp/restful-snap
    commit: 5f5e91dc7ce0e5e624a61998ede71e211262f26e
  extra-dep: true
- location:
    git: https://github.com/dbp/groundhog-utils
    commit: 29fb9d90aeda85bf5b9126a36b1448f9d4af50b1
  extra-dep: true
extra-deps:
- aeson-0.9.0.1
- bytestring-builder-0.10.8.1.0
- conduit-extra-1.1.13.2
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- haskell-docs-4.2.6
- heist-0.14.1.3
- kan-extensions-5.0.1
- lens-4.13.2.1
- postgresql-simple-0.5.2.1
- snap-extras-0.11.0.2
- snap-loader-static-0.9.0.2
- text-1.2.2.1
- yaml-0.8.18
- applicative-quoters-0.1.0.8
resolver: lts-6.5
